# .github/workflows/run-on-tag.yml
name: Build & Deploy on tag from main

on:
  push:
    tags:
      - '*'   # run on any tag push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/') && github.event.base_ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.4.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify AWS CLI
        run: aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.PUBLISHING_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PUBLISHING_SECRET_KEY }}

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://evindunn.com/ --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ENQKSR25Q85 --paths '/'
